image:
  file: .gitpod.Dockerfile

jetbrains:
  phpstorm:
    plugins:
      - fr.adrienbrault.idea.symfony2plugin

tasks:
  - init: |
      composer install;
      yarn install && yarn run build;
    command: |
      sudo chsh -s /usr/bin/fish;
      exec fish;
