image:
  file: .gitpod.Dockerfile

ports:
  - port: 11374
    onOpen: open-browser
  - port: 11380
    onOpen: open-browser
  - port: 11381
    onOpen: open-browser
  - port: 33674
    onOpen: open-browser
  - port: 33680
    onOpen: open-browser
  - port: 33681
    onOpen: open-browser
  - port: 11100
    onOpen: notify

tasks:
  - init: |
      composer install --no-interaction --no-ansi --no-progress;
      yarn install;
      yarn run build;
      ./dev docker-build;
      ./dev docker-up;
