version: '3.7'

services:
  ansel-craft3-php74:
    image: nginx:1.21.6
    container_name: ansel-craft3-php74
    environment:
      HOSTNAME: ansel-craft3-php74
    expose:
      - 80
    ports:
      - "11374:80"
    volumes:
      - ./.profile:/root/.profile
      - ./.profile:/root/.bashrc
      - ./nginx/ansel-craft3-php74.conf:/etc/nginx/conf.d/default.conf
      - ./environments/craft3:/var/www/craft3

  ansel-craft3-php80:
    image: nginx:1.21.6
    container_name: ansel-craft3-php80
    environment:
      HOSTNAME: ansel-craft3-php80
    expose:
      - 80
    ports:
      - "11380:80"
    volumes:
      - ./.profile:/root/.profile
      - ./.profile:/root/.bashrc
      - ./nginx/ansel-craft3-php80.conf:/etc/nginx/conf.d/default.conf
      - ./environments/craft3:/var/www/craft3

  ansel-craft3-php81:
    image: nginx:1.21.6
    container_name: ansel-craft3-php81
    environment:
      HOSTNAME: ansel-craft3-php81
    expose:
      - 80
    ports:
      - "11381:80"
    volumes:
      - ./.profile:/root/.profile
      - ./.profile:/root/.bashrc
      - ./nginx/ansel-craft3-php81.conf:/etc/nginx/conf.d/default.conf
      - ./environments/craft3:/var/www/craft3

  ansel-ee6-php74:
    image: nginx:1.21.6
    container_name: ansel-ee6-php74
    environment:
      HOSTNAME: ansel-ee6-php74
    expose:
      - 80
    ports:
      - "33674:80"
    volumes:
      - ./.profile:/root/.profile
      - ./.profile:/root/.bashrc
      - ./nginx/ansel-ee6-php74.conf:/etc/nginx/conf.d/default.conf
      - ./environments/ee6:/var/www/ee6

  ansel-ee6-php80:
    image: nginx:1.21.6
    container_name: ansel-ee6-php80
    environment:
      HOSTNAME: ansel-ee6-php80
    expose:
      - 80
    ports:
      - "33680:80"
    volumes:
      - ./.profile:/root/.profile
      - ./.profile:/root/.bashrc
      - ./nginx/ansel-ee6-php80.conf:/etc/nginx/conf.d/default.conf
      - ./environments/ee6:/var/www/ee6

  ansel-ee6-php81:
    image: nginx:1.21.6
    container_name: ansel-ee6-php81
    environment:
      HOSTNAME: ansel-ee6-php81
    expose:
      - 80
    ports:
      - "33681:80"
    volumes:
      - ./.profile:/root/.profile
      - ./.profile:/root/.bashrc
      - ./nginx/ansel-ee6-php81.conf:/etc/nginx/conf.d/default.conf
      - ./environments/ee6:/var/www/ee6

  ansel-php74:
    build:
      context: .
      dockerfile: ./php74/Dockerfile
    container_name: ansel-php74
    environment:
      HOSTNAME: ansel-php74
      CRAFT_ALLOW_SUPERUSER: 1
    volumes:
      - ./environments:/var/www
    networks:
      default:
        aliases:
          - ansel-php74

  ansel-php80:
    build:
      context: .
      dockerfile: ./php80/Dockerfile
    container_name: ansel-php80
    environment:
      HOSTNAME: ansel-php80
      CRAFT_ALLOW_SUPERUSER: 1
    volumes:
      - ./environments:/var/www
    networks:
      default:
        aliases:
          - ansel-php80

  ansel-php81:
    build:
      context: .
      dockerfile: ./php81/Dockerfile
    container_name: ansel-php81
    environment:
      HOSTNAME: ansel-php81
      CRAFT_ALLOW_SUPERUSER: 1
    volumes:
      - ./environments:/var/www
    networks:
      default:
        aliases:
          - ansel-php81

  db:
    image: mariadb:10.7.1
    container_name: ansel-db
    environment:
      HOSTNAME: ansel-db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "11100:3306"
    networks:
      default:
        aliases:
          - ansel-db
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
