version: '3.7'

services:
  ansel-nginx:
    env_file:
      - .env
    image: nginx:1.21.6
    container_name: ansel-nginx
    environment:
      HOSTNAME: ansel-nginx
    expose:
      - 80
    ports:
      - "11374:11374"
      - "11380:11380"
      - "11381:11381"
      - "33774:33774"
      - "33780:33780"
      - "33781:33781"
      - "9980:9980"
      - "9981:9981"
    volumes: &customVolumes
      - ./nginx:/etc/nginx/conf.d
      - ./.profile:/root/.profile
      - ./.profile:/root/.bashrc
      - ./environments:/var/www
      - ../:/var/www/ansel
      ## EE 7 Mounts
      - ../cms/ExpressionEngine:/var/www/ee7/system/user/addons/ansel
      - ../assetsDist:/var/www/ee7/public/themes/user/ansel
      - ../composer.json:/var/www/ee7/system/user/addons/ansel/composer.json
      - ../composer.lock:/var/www/ee7/system/user/addons/ansel/composer.lock
      - ../config:/var/www/ee7/system/user/addons/ansel/config
      - ../src:/var/www/ee7/system/user/addons/ansel/src
      - ee7-ansel-vendor:/var/www/ee7/system/user/addons/ansel/vendor
      ## Coilpack Mounts
      - ../cms/ExpressionEngine:/var/www/eecoilpack/ee/system/user/addons/ansel
      - ../assetsDist:/var/www/eecoilpack/ee/themes/user/ansel
      - ../composer.json:/var/www/eecoilpack/ee/system/user/addons/ansel/composer.json
      - ../composer.lock:/var/www/eecoilpack/ee/system/user/addons/ansel/composer.lock
      - ../config:/var/www/eecoilpack/ee/system/user/addons/ansel/config
      - ../src:/var/www/eecoilpack/ee/system/user/addons/ansel/src
      - coilpack-ansel-vendor:/var/www/eecoilpack/ee/system/user/addons/ansel/vendor
    networks:
      web:
      default:

  ansel-php74:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./php74/Dockerfile
    container_name: ansel-php74
    environment:
      HOSTNAME: ansel-php74
      CRAFT_ALLOW_SUPERUSER: 1
    volumes: *customVolumes
    networks:
      default:
        aliases:
          - ansel-php74

  ansel-php80:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./php80/Dockerfile
    container_name: ansel-php80
    environment:
      HOSTNAME: ansel-php80
      CRAFT_ALLOW_SUPERUSER: 1
    volumes: *customVolumes
    networks:
      default:
        aliases:
          - ansel-php80

  ansel-php81:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./php81/Dockerfile
    container_name: ansel-php81
    environment:
      HOSTNAME: ansel-php81
      CRAFT_ALLOW_SUPERUSER: 1
    volumes: *customVolumes
    networks:
      default:
        aliases:
          - ansel-php81

  db:
    env_file:
      - .env
    image: mariadb:10.7.1
    container_name: ansel-db
    environment:
      HOSTNAME: ansel-db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "11100:3306"
    networks:
      default:
        aliases:
          - ansel-db
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
  ee7-ansel-vendor:
  coilpack-ansel-vendor:

networks:
  web:
    name: traefik-dev_default
