version: '3.7'

services:
  ansel-nginx:
    image: nginx:1.21.6
    container_name: ansel-nginx
    environment:
      HOSTNAME: ansel-nginx
    expose:
      - 80
    ports:
      - "11374:11374"
      - "11380:11380"
      - "11381:11381"
      - "33674:33674"
      - "33774:33774"
      - "33680:33680"
      - "33780:33780"
      - "33681:33681"
      - "33781:33781"
    volumes:
      - ./nginx/anselcraftphp74.conf:/etc/nginx/conf.d/anselcraftphp74.conf
      - ./nginx/anselcraftphp80.conf:/etc/nginx/conf.d/anselcraftphp80.conf
      - ./nginx/anselcraftphp81.conf:/etc/nginx/conf.d/anselcraftphp81.conf
      - ./nginx/anseleephp74.conf:/etc/nginx/conf.d/anseleephp74.conf
      - ./nginx/anseleephp80.conf:/etc/nginx/conf.d/anseleephp80.conf
      - ./nginx/anseleephp81.conf:/etc/nginx/conf.d/anseleephp81.conf
      - ./nginx/anselee7php74.conf:/etc/nginx/conf.d/anselee7php74.conf
      - ./nginx/anselee7php80.conf:/etc/nginx/conf.d/anselee7php80.conf
      - ./nginx/anselee7php81.conf:/etc/nginx/conf.d/anselee7php81.conf
      - ./.profile:/root/.profile
      - ./.profile:/root/.bashrc
      - ./environments/craft3:/var/www/craft3
      - ./environments/ee6:/var/www/ee6
      - ./environments/ee7:/var/www/ee7
      - ../:/var/www/ansel
#      - ./environments/ee6/vendor/expressionengine/expressionengine/system/ee:/var/www/ee6/system/ee
#      - ./environments/ee6/vendor/expressionengine/expressionengine/images:/var/www/ee6/public/images
#      - ./environments/ee6/vendor/expressionengine/expressionengine/themes/ee:/var/www/ee6/public/themes/ee
      - ../cms/ExpressionEngine:/var/www/ee6/system/user/addons/ansel
      - ../assetsDist:/var/www/ee6/public/themes/user/ansel
      - ../composer.json:/var/www/ee6/system/user/addons/ansel/composer.json
      - ../composer.lock:/var/www/ee6/system/user/addons/ansel/composer.lock
      - ../config:/var/www/ee6/system/user/addons/ansel/config
      - ../src:/var/www/ee6/system/user/addons/ansel/src
      - ../vendor:/var/www/ee6/system/user/addons/ansel/vendor
      - ../cms/ExpressionEngine:/var/www/ee7/system/user/addons/ansel
      - ../assetsDist:/var/www/ee7/public/themes/user/ansel
      - ../composer.json:/var/www/ee7/system/user/addons/ansel/composer.json
      - ../composer.lock:/var/www/ee7/system/user/addons/ansel/composer.lock
      - ../config:/var/www/ee7/system/user/addons/ansel/config
      - ../src:/var/www/ee7/system/user/addons/ansel/src
      - ../vendor:/var/www/ee7/system/user/addons/ansel/vendor
    networks:
      web:
      default:
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-dev_default
      - traefik.http.routers.ansel.entrypoints=web
      - traefik.http.routers.ansel.rule=Host(`anseleephp74.localtest.me`,`anseleephp74.test`,`anseleephp80.localtest.me`,`anseleephp80.test`,`anseleephp81.localtest.me`,`anseleephp81.test`,`anselcraftphp74.localtest.me`,`anselcraftphp74.test`,`anselcraftphp80.localtest.me`,`anselcraftphp80.test`,`anselcraftphp81.localtest.me`,`anselcraftphp81.test`,`anselee7php74.localtest.me`,`anselee7php74.test`,`anselee7php80.localtest.me`,`anselee7php80.test`,`anselee7php81.localtest.me`,`anselee7php81.test`)

  ansel-php74:
    build:
      context: .
      dockerfile: ./php74/Dockerfile
    container_name: ansel-php74
    environment:
      HOSTNAME: ansel-php74
      CRAFT_ALLOW_SUPERUSER: 1
    volumes: &phpVolumes
      - ./environments:/var/www
      - ../:/var/www/ansel
#      - ./environments/ee6/vendor/expressionengine/expressionengine/system/ee:/var/www/ee6/system/ee
#      - ./environments/ee6/vendor/expressionengine/expressionengine/images:/var/www/ee6/public/images
#      - ./environments/ee6/vendor/expressionengine/expressionengine/themes/ee:/var/www/ee6/public/themes/ee
      - ../cms/ExpressionEngine:/var/www/ee6/system/user/addons/ansel
      - ../assetsDist:/var/www/ee6/public/themes/user/ansel
      - ../composer.json:/var/www/ee6/system/user/addons/ansel/composer.json
      - ../composer.lock:/var/www/ee6/system/user/addons/ansel/composer.lock
      - ../config:/var/www/ee6/system/user/addons/ansel/config
      - ../src:/var/www/ee6/system/user/addons/ansel/src
      - ../vendor:/var/www/ee6/system/user/addons/ansel/vendor
      - ../cms/ExpressionEngine:/var/www/ee7/system/user/addons/ansel
      - ../assetsDist:/var/www/ee7/public/themes/user/ansel
      - ../composer.json:/var/www/ee7/system/user/addons/ansel/composer.json
      - ../composer.lock:/var/www/ee7/system/user/addons/ansel/composer.lock
      - ../config:/var/www/ee7/system/user/addons/ansel/config
      - ../src:/var/www/ee7/system/user/addons/ansel/src
      - ../vendor:/var/www/ee7/system/user/addons/ansel/vendor
    networks:
      default:
        aliases:
          - ansel-php74

  ansel-php80:
    build:
      context: .
      dockerfile: ./php80/Dockerfile
    container_name: ansel-php80
    environment:
      HOSTNAME: ansel-php80
      CRAFT_ALLOW_SUPERUSER: 1
    volumes: *phpVolumes
    networks:
      default:
        aliases:
          - ansel-php80

  ansel-php81:
    build:
      context: .
      dockerfile: ./php81/Dockerfile
    container_name: ansel-php81
    environment:
      HOSTNAME: ansel-php81
      CRAFT_ALLOW_SUPERUSER: 1
    volumes: *phpVolumes
    networks:
      default:
        aliases:
          - ansel-php81

  db:
    image: mariadb:10.7.1
    container_name: ansel-db
    environment:
      HOSTNAME: ansel-db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "11100:3306"
    networks:
      default:
        aliases:
          - ansel-db
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:

networks:
  web:
    name: traefik-dev_default
