/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

module.exports = function(grunt) {
	// Set grunt config for clean
	grunt.fabInitConfig.clean = {
		cssLib: grunt.fabConfig.assets + '/css/lib/**/*',
		jsLib: grunt.fabConfig.assets + '/js/lib/**/*',
		images: grunt.fabConfig.assets + '/img/**/*',
		fonts: grunt.fabConfig.assets + '/fonts/**/*',
		moduleCssLib: grunt.fabConfig.assets + '/modules/**/css/lib/**/*',
		moduleJsLib: grunt.fabConfig.assets + '/modules/**/js/lib/**/*',
		moduleImages: grunt.fabConfig.assets + '/modules/**/img/**/*',
		moduleFonts: grunt.fabConfig.assets + '/modules/**/fonts/**/*',
		moduleFiles: grunt.fabConfig.assets + '/modules/**/files/**/*'
	};
};
