/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

module.exports = function(grunt) {
	// Register initial cleanup task
	grunt.registerTask('initialCleanup', function() {
		// Delete compile cache
		if (grunt.file.exists(grunt.fabConfig.source + '/coreFAB/compileCache/js/')) {
			grunt.file.delete(grunt.fabConfig.source + '/coreFAB/compileCache/js/');
		}

		// Write version file
		grunt.file.write(grunt.fabConfig.source + '/coreFAB/compileCache/js/version.js', '$(function() {window.TREASURY = window.TREASURY || {};window.TREASURY.version = "' + grunt.fabPackage.version + '";});');

		// Delete JS files
		if (grunt.file.exists(grunt.fabConfig.assets + '/js/')) {
			grunt.file.delete(grunt.fabConfig.assets + '/js/');
		}

		// Delete CSS files
		if (grunt.file.exists(grunt.fabConfig.assets + '/css/')) {
			grunt.file.delete(grunt.fabConfig.assets + '/css/');
		}

		// Delete font files
		if (grunt.file.exists(grunt.fabConfig.assets + '/fonts/')) {
			grunt.file.delete(grunt.fabConfig.assets + '/fonts/');
		}

		// Delete images
		if (grunt.file.exists(grunt.fabConfig.assets + '/img/')) {
			grunt.file.delete(grunt.fabConfig.assets + '/img/');
		}

		// Delete module files
		if (grunt.file.exists(grunt.fabConfig.assets + '/modules/')) {
			grunt.file.delete(grunt.fabConfig.assets + '/modules/');
		}
	});
};
