/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

module.exports = function(grunt) {
	// Set grunt config for jshint
	grunt.fabInitConfig.jshint = {
		files: [
			grunt.fabConfig.source + '/js/**/*.js',
			'!' + grunt.fabConfig.source + '/js/lib/**/*.js',
			grunt.fabConfig.source + '/modules/*/*/js/**/*.js',
			'!' + grunt.fabConfig.source + '/modules/*/*/js/lib/**/*.js'
		],
		options: {
			jshintrc: true
		}
	};
};
