/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

module.exports = function(grunt) {
	// Set up primary CSS file
	var primaryCssFile = grunt.fabConfig.assets + '/css/style.min.css';
	var lessFiles = {};

	// Add primary source
	lessFiles[primaryCssFile] = [
		grunt.fabConfig.source + '/coreFAB/css/fab.less'
	];

	// Check if there are any build files from project file
	if (grunt.fabConfig.lessBuild.length) {
		// Loop through the build files array
		grunt.fabConfig.lessBuild.forEach(function(i) {
			// Push the file into the compile array
			lessFiles[primaryCssFile].push(i);
		});
	}

	// Check if there are individual less files
	if (Object.keys(grunt.fabConfig.lessFiles).length) {
		// Loop through the individual files
		for (var key in grunt.fabConfig.lessFiles) {
			// Add individual Less file to the array to be compiled
			lessFiles[grunt.fabConfig.assets + '/css/' + key] = grunt.fabConfig.lessFiles[key];
		}
	}

	// Add module compile files
	grunt.file.expand(grunt.fabConfig.source + '/modules/compile/*').forEach(function(i) {
		var moduleName = i.split('/').pop();

		// Configure module Less
		lessFiles[grunt.fabConfig.assets + '/modules/' + moduleName + '/css/style.min.css'] = i + '/css/module.less';
	});

	// Set grunt config for less
	grunt.fabInitConfig.less = {
		development: {
			options: {
				compress: grunt.fabConfig.lessCompress,
				yuicompress: grunt.fabConfig.lessCompress,
				optimization: 2,
				plugins: [
					require('less-plugin-glob')
				]
			},
			files: lessFiles
		}
	};
};
