/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

module.exports = function(grunt) {
	// Register grunt compile task
	grunt.registerTask('compile', [
		'initialCleanup',
		'copy',
		'less',
		'uglify',
		'notify:less',
		'notify:uglify'
	]);

	// Register default task
	grunt.registerTask('default', [
		'compile',
		'browserSync',
		'watch'
	]);

	// Register check task
	grunt.registerTask('check', [
		'http:check'
	]);

	// Register update task
	grunt.registerTask('update', [
		'http:check',
		'curl:downloadUpdate',
		'unzip:update',
		'updateFiles'
	]);
};
