/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

module.exports = function(grunt) {
	// Set grunt config for unzip
	grunt.fabInitConfig.unzip = {
		update: {
			src: grunt.fabConfig.source + '/coreFAB/compileCache/release.zip',
			dest: 'FABRELEASE'
		}
	};
};
