/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

module.exports = function(grunt) {
	// Grunt register createBuildModule task
	grunt.registerTask('updateFiles', function() {
		grunt.file.expand('FABRELEASE/*').forEach(function(file) {
			// Delete the coreFAB directory
			grunt.file.delete(grunt.fabConfig.source + '/coreFAB');

			// Loop through coreFAB files (including hidden files)
			grunt.file.expand([
				file + '/assetsSource/coreFAB/**/*',
				file + '/assetsSource/coreFAB/**/.*'
			]).forEach(function(sourceFile) {
				// Get the filename
				var fileName = sourceFile.replace(file + '/assetsSource/coreFAB/', '');

				// Make sure this is a file and not a directory
				if (grunt.file.isFile(sourceFile)) {
					// Copy the file into place
					grunt.file.copy(
						sourceFile,
						grunt.fabConfig.source + '/coreFAB/' + fileName
					);
				}
			});

			// Delete grunt file
			grunt.file.delete('Gruntfile.js');

			// Copy new grunt file
			grunt.file.copy(
				file + '/Gruntfile.js',
				'Gruntfile.js'
			);

			// Delete package file
			grunt.file.delete('package.json');

			// Copy new package file
			grunt.file.copy(
				file + '/package.json',
				'package.json'
			);

			// Clean up
			grunt.file.delete('FABRELEASE');

			grunt.log.ok('Fabricator has been updated successfully');
			grunt.log.ok('Please run "npm update" in case Fabricator requires any new NPM Modules');
		});
	});
};
