/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

module.exports = function(grunt) {
	var key;
	var lessFiles = [
		grunt.fabConfig.source + '/coreFAB/css/**/*',
		grunt.fabConfig.source + '/css/**/*',
		grunt.fabConfig.source + '/modules/*/*/css/**/*'
	];
	var jsFiles = [
		grunt.fabConfig.source + '/coreFAB/js/**/*',
		grunt.fabConfig.source + '/js/**/*',
		grunt.fabConfig.source + '/modules/*/*/js/**/*'
	];

	// Add any less build files from project file
	if (grunt.fabConfig.lessBuild.length) {
		// Loop through the build files array
		grunt.fabConfig.lessBuild.forEach(function(i) {
			// Push the file into the array to be watched
			lessFiles.push(i);
		});
	}

	// Add individual less files
	if (Object.keys(grunt.fabConfig.lessFiles).length) {
		// Loop through the individual files
		for (key in grunt.fabConfig.lessFiles) {
			// Add individual Less file to the array to be watched
			lessFiles.push(grunt.fabConfig.lessFiles[key]);
		}
	}

	// Check for build before files in project file
	if (grunt.fabConfig.jsBuildBefore.length) {
		// Loop through the build before files
		grunt.fabConfig.jsBuildBefore.forEach(function(i) {
			// Push the file into the array to be watched
			jsFiles.push(i);
		});
	}

	// Check for build files in the project file
	if (grunt.fabConfig.jsBuild.length) {
		// Loop through the build files
		grunt.fabConfig.jsBuild.forEach(function(i) {
			// Push the file into the array to be watched
			jsFiles.push(i);
		});
	}

	// Check for build after files
	if (grunt.fabConfig.jsBuildAfter.length) {
		// Loop through the build after files
		grunt.fabConfig.jsBuildAfter.forEach(function(i) {
			// Push the file into the array to be watched
			jsFiles.push(i);
		});
	}

	// Check if there are individual javascript files to compile in project file
	if (Object.keys(grunt.fabConfig.jsFiles).length) {
		// Loop through the files
		for (key in grunt.fabConfig.jsFiles) {
			// Add individual Less file to the array to be watched
			lessFiles.push(grunt.fabConfig.jsFiles[key]);
		}
	}

	// Set grunt config for watch
	grunt.fabInitConfig.watch = {
		styles: {
			files: lessFiles,
			tasks: [
				'less',
				'notify:less'
			],
			options: {
				spawn: false
			}
		},
		javascript: {
			files: jsFiles,
			tasks: [
				'uglify',
				'notify:uglify'
			],
			options: {
				spawn: false
			}
		},
		jshint: {
			files: [
				'<%= jshint.files %>'
			],
			tasks: [
				'jshint'
			],
			options: {
				spawn: false
			}
		},
		jscs: {
			files: [
				'<%= jscs.src %>'
			],
			tasks: [
				'jscs'
			],
			options: {
				spawn: false
			}
		},

		/**
		 * File copying
		 */
		cssLib: {
			files: grunt.fabConfig.source + '/css/lib/**',
			tasks: [
				'clean:cssLib',
				'copy:cssLib'
			],
			options: {
				spawn: false
			}
		},
		jsLib: {
			files: grunt.fabConfig.source + '/js/lib/**',
			tasks: [
				'clean:jsLib',
				'copy:jsLib'
			],
			options: {
				spawn: false
			}
		},
		images: {
			files: grunt.fabConfig.source + '/img/**',
			tasks: [
				'clean:images',
				'copy:images'
			],
			options: {
				spawn: false
			}
		},
		fonts: {
			files: grunt.fabConfig.source + '/fonts/**',
			tasks: [
				'clean:fonts',
				'copy:fonts'
			],
			options: {
				spawn: false
			}
		},
		moduleBuildCssLib: {
			files: grunt.fabConfig.source + '/modules/build/**/css/lib/**',
			tasks: [
				'clean:moduleCssLib',
				'copy:moduleBuildCssLib'
			],
			options: {
				spawn: false
			}
		},
		moduleBuildJsLib: {
			files: grunt.fabConfig.source + '/modules/build/**/js/lib/**',
			tasks: [
				'clean:moduleJsLib',
				'copy:moduleBuildJsLib'
			],
			options: {
				spawn: false
			}
		},
		moduleBuildImages: {
			files: grunt.fabConfig.source + '/modules/build/**/img/**',
			tasks: [
				'clean:moduleImages',
				'copy:moduleBuildImages'
			],
			options: {
				spawn: false
			}
		},
		moduleBuildFonts: {
			files: grunt.fabConfig.source + '/modules/build/**/fonts/**',
			tasks: [
				'clean:moduleFonts',
				'copy:moduleBuildFonts'
			],
			options: {
				spawn: false
			}
		},
		moduleBuildFiles: {
			files: grunt.fabConfig.source + '/modules/build/**/files/**',
			tasks: [
				'clean:moduleFiles',
				'copy:moduleBuildFiles'
			],
			options: {
				spawn: false
			}
		},
		moduleCompileCssLib: {
			files: grunt.fabConfig.source + '/modules/compile/**/css/lib/**',
			tasks: [
				'clean:moduleCssLib',
				'copy:moduleCompileCssLib'
			],
			options: {
				spawn: false
			}
		},
		moduleCompileJsLib: {
			files: grunt.fabConfig.source + '/modules/compile/**/js/lib/**',
			tasks: [
				'clean:moduleJsLib',
				'copy:moduleCompileJsLib'
			],
			options: {
				spawn: false
			}
		},
		moduleCompileImages: {
			files: grunt.fabConfig.source + '/modules/compile/**/img/**',
			tasks: [
				'clean:moduleImages',
				'copy:moduleCompileImages'
			],
			options: {
				spawn: false
			}
		},
		moduleCompileFonts: {
			files: grunt.fabConfig.source + '/modules/compile/**/fonts/**',
			tasks: [
				'clean:moduleFonts',
				'copy:moduleCompileFonts'
			],
			options: {
				spawn: false
			}
		},
		moduleCompileFiles: {
			files: grunt.fabConfig.source + '/modules/compile/**/files/**',
			tasks: [
				'clean:moduleFiles',
				'copy:moduleCompileFiles'
			],
			options: {
				spawn: false
			}
		}
	};
};
